### ISSUE TITLE
Can we support 1.6.1?

### ISSUE THREAD

**Issue by sdbds** [Carzit/sd-webui-samplers-scheduler#1]
Today i read paper and find this page,but i cant use it in 1.6.1...
Even i switch to 1.5.2,it still happended errors.

Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-webui-aki-v4.1\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.1\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 794, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 1054, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_kdiffusion.py", line 464, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_kdiffusion.py", line 303, in launch_sampling
        return func()
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_kdiffusion.py", line 464, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\sd-webui-aki-v4.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-samplers-scheduler\scripts\Seniorious.py", line 811, in seniorious
        x_ = samplers[i](model=model, x=x_, sigmas=s, extra_args=extra_args, callback=callback_)
    TypeError: 'NoneType' object is not callable

**Comment by Carzit** [comment]
Hello, thank you for submitting the issue! 

In version 1.5.2, since I pass the sampler configuration adjusted by the gradio slider through a global list maintained in the extension script, there may be some synchronization/asynchronization issues here that make the list update inconsistent with the slider in some cases, making it difficult to zero out the step settings for some sampler empty unit (e.g. You once used this unit. Now you don't need it and turn the sampler setting to None). I've run into it sometimes too. 
I'm trying to fix this. Alternatives until fixed: Change dragging the slider bar to typing the number directly in the corresponding number box
(if it doesn't work, restart the WebUI)

Regarding support sd webui 1.6.1, I am checking a1111's changelog. While the sampler section seems to just add a couple of new samplers according to him, he seems to have tweaked some of the architecture so that the original function to register sampler  just produces confusing results. My code implementation was based on https://github.com/hnmr293/sd-webui-sd-webui-DPMPP_2M_Karras_v2, which fails after the 1.6.1 update as described above. 

If possible, does anyone has a solution to add sampler by extension in 1.6.1? QAQ

**Comment by Carzit** [comment]
The problem of NoneType** caused by UI info updates has been preliminarily solved in #2 .

And Seniorious can be used in sd webui 1.6.0 and 1.6.1 now
https://github.com/Carzit/sd-webui-samplers-scheduler-for-v1.6

Unfortunately, due to architectural changes, it is difficult for extensions for v1.6.x to be backward compatible.
Further I'll try to make the extension program automatically use the corresponding script according to the sd webui version

**Comment by sdbds** [comment]
> The problem of NoneType** caused by UI info updates has been preliminarily solved in #2 .
> 
> And Seniorious can be used in sd webui 1.6.0 and 1.6.1 now https://github.com/Carzit/sd-webui-samplers-scheduler-for-v1.6
> 
> Unfortunately, due to architectural changes, it is difficult for extensions for v1.6.x to be backward compatible. Further I'll try to make the extension program automatically use the corresponding script according to the sd webui version

it works now~ Thank u
